### ISSUE TITLE
CI build failing

### ISSUE THREAD

**Issue by ThomasKroes** [ManiVaultStudio/ImageLoaderPlugin#90]
The CI build for [release/core_1.0rc/0.3](https://github.com/ManiVaultStudio/ImageLoaderPlugin/tree/release/core_1.0rc/0.3) is [failing](https://github.com/ManiVaultStudio/ImageLoaderPlugin/actions/runs/8122352892/job/22201703833):

`
ERROR: Missing binary: freeimage/3.18.0@lkeb/stable:4747336be67aecdf5549d190a0cb9f3dedfcd57c
freeimage/3.18.0@lkeb/stable: WARN: Can't find a 'freeimage/3.18.0@lkeb/stable' package for the specified settings, options and dependencies:
`

, despite the changes below:
```
matrix:
    include:
      - name: Windows-msvc2019
        os: windows-2019
        compiler: msvc-2019
        build-cversion: 16
        build-runtime: MD
        build-config: Release
      - name: Linux_gcc11
        os: ubuntu-22.04
        build-cc: gcc
        build-cxx: g++
        build-compiler: gcc
        build-cversion: 11
        build-config: Release
        build-os: Linux
        build-libcxx: libstdc++
      - name: Macos_xcode13.4
        os: macos-12
        build-compiler: apple-clang
        build-cversion: 13
        build-config: Release
        build-os: Macos
        build-xcode-version: 13.4
        build-libcxx: libc++
```
